Music/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
app_name = 'Music'


urlpatterns = [

    #/music/
    path('', views.IndexView.as_view(), name='index'),

    path('register/', views.UserFormView.as_view(), name='register'),

    #/music/<album_id>/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

    #/music/album/2/
    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='album-update'),

    #/music/album/2/delete/
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),

]

website/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from  django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('Music.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Music/models.py
from django.db import models
from django.urls import reverse


class Albums(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('Music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Playlist(models.Model):





class Song(models.Model):
    album = models.ForeignKey(Albums, on_delete=models.CASCADE)
    file_key = models.CharField(max_length=100)
    song_title = models.CharField(max_length=250)


    def __str__(self):
        return self.song_title

Music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .models import Albums
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Albums.objects.all()


class DetailView(generic.DetailView):
    model = Albums
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Albums
    fields = ['artist', 'genre', 'album_title', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Albums
    fields = ['artist', 'genre', 'album_title', 'album_logo']


class AlbumDelete(DeleteView):
    model = Albums
    success_url = reverse_lazy('Music:index')
    fields = ['artist', 'genre', 'album_title', 'album_logo']


class UserFormView(View):
    form_class = UserForm
    template_name = 'Music/registration_form.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            #cleaned (normalized) data

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns Usr Objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return  redirect('Music:index')

        return render(request, self.template_name, {'form': form})

Music/templates/Music/albums_form.html
{% extends 'Music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Music/templates/Music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Rhythm{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-default">

    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Music:index' %}">Rhythm</a>
        </div>

        <!-- individual items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'Music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'Music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Music/templates/Music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}
    <img src="{{ albums.album_logo.url }}", alt = "Size is larger than expected"/>

    <h1>{{ albums.album_title }}</h1>>
    <h2>{{ albums.artist }}</h2>



    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'Music:detail' albums.id %}" method="post">
        {% csrf_token %}
        {% for song in albums.song_set.all %}

            <label for="song{{ forloop.counter }}">
                <li>{{ song.song_title }}</li>
            </label><br>
        {% endfor %}
    </form>
{% endblock %}

Music/templates/Music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

Music/templates/Music/index.html
{% extends 'Music/base.html' %}


{% block title %}Rhythm{% endblock %}


{% block body %}
    <div class="albums-container container-fluid">

    <!-- Albums -->
                <div class="container-fluid">

                    {% if all_albums %}
                        {% for album in all_albums %}
                            <div class="col-sm-4 col-lg-2">
                                <div class="circle">
                                    <a href="{% url  'Music:detail'  album.id %}">
                                        <img src="{{ album.album_logo.url }}" class="img-responsive">
                                    </a>
                                    <div class="caption">
                                        <h2>{{ album.album_title }}</h2>
                                        <h4>{{ album.artist }}</h4>

                                        <!-- View Details -->
                                        <a href="{% url 'Music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                                        <!-- Delete Album -->
                                        <form action="{% url 'Music:album-delete' album.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                                            <button type="submit" class="btn btn-default btn-sm">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                        </form>



                                    </div>
                                </div>
                            </div>
                            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                        {% endfor %}
                    {% else %}
                        <div class="col-sm-12">
                            <br>
                            <a href="{% url 'Music:album-add' %}">
                                <button type="button" class="btn btn-success">
                                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                                </button>
                            </a>
                        </div>
                    {% endif %}
                </div>

    </div>


{% endblock %}

Music/templates/Music/registration_form.html
{% extends 'Music/base.html' %}
{% block title %}Registration{% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}